version: '3.7'

services:
  db:
    container_name: postgres-greenatoom
    image: postgres:12
    restart: on-failure
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin-greenatom
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db

  api:
    container_name: greenatom-api
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 8000:8000
    command: uvicorn main:app --reload --host 0.0.0.0
    restart: on-failure
    depends_on:
      - db
      - minio

  minio:
    restart: always
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    env_file: .env
    volumes:
      - minio-storage:/data

volumes:
  minio-storage: