"""4

Revision ID: 2272d1c1360e
Revises: 9f9d0b6ece8b
Create Date: 2022-06-14 19:23:32.860766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2272d1c1360e'
down_revision = '9f9d0b6ece8b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
