"""add user table

Revision ID: 3ba3d8992da9
Revises: 9ec4a28f956c
Create Date: 2022-06-15 13:39:25.167691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ba3d8992da9'
down_revision = '9ec4a28f956c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
