"""requests add column user_id

Revision ID: 3fe29dad938a
Revises: 3ba3d8992da9
Create Date: 2022-06-15 13:50:59.605729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fe29dad938a'
down_revision = '3ba3d8992da9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_requests_user_id'), 'requests', ['user_id'], unique=False)
    op.create_foreign_key(None, 'requests', 'requests', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'requests', type_='foreignkey')
    op.drop_index(op.f('ix_requests_user_id'), table_name='requests')
    op.drop_column('requests', 'user_id')
    # ### end Alembic commands ###
