"""inbox nullable

Revision ID: 9ec4a28f956c
Revises: 2272d1c1360e
Create Date: 2022-06-14 19:24:49.282980

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9ec4a28f956c'
down_revision = '2272d1c1360e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inboxes', 'request_code',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('inboxes', 'file_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('inboxes', 'datetime',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inboxes', 'datetime',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('inboxes', 'file_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('inboxes', 'request_code',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
