"""add requests table

Revision ID: e05bdd1fc7bb
Revises: 
Create Date: 2022-06-14 18:14:37.783720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e05bdd1fc7bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inboxes', sa.Column('id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_inboxes_id'), 'inboxes', ['id'], unique=False)
    op.create_foreign_key(None, 'inboxes', 'requests', ['request_code'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inboxes', type_='foreignkey')
    op.drop_index(op.f('ix_inboxes_id'), table_name='inboxes')
    op.drop_column('inboxes', 'id')
    # ### end Alembic commands ###
